version: "3"

services:
  balancer:
    image: golang:1.19-alpine
    volumes:
      - .:/go

    command: ./go/balancer
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mongo:4.2.8
    volumes:
      - .data:/data/db
      - .data/conf:/data/configdb